#' Apply upsimpler on a selection of target samples
#'
#' Function to apply the upsimpler algorithm on a single dataset.
#' Given a list of target samples, this function generates the requested number of synthetic samples
#' per target sample (seed) and returns them as a single dataframe.
#'
#' @param upsimpler The (already initialized) upsimpler object to be used for generating the synthetic samples.
#' @param upsimplerUsedArgs List of arguments to be passed to the upsimpler algorithm.
#' @param metadataDF Dataframe containing the metadata of the samples (samples as rows).
#' @param targetSampleIDs List of sample IDs to be used as seed for the upsimpler algorithm.
#' Must be present in the dataDF and metadataDF in upsimplerUsedArgs.
#' @param classColumn Column name in the metadata dataframe containing the class information.
#' @param sampleColumn Column name in the metadata dataframe containing the sample identifier.
#'
#' @return Dataframe containing the synthetic samples generated by the upsimpler algorithm
#' for all target samples (seeds) combined ($synthDataDF), as well as the metadata of the synthetic samples ($synthMetadataDF).
#' The metadata contain only the class information of the synthetic samples.
#' @export
#'
applyUpsimpler <- function(upsimpler,
                           upsimplerUsedArgs,
                           metadataDF,
                           targetSampleIDs,
                           classColumn,
                           higherClassColumn,
                           domainColumn,
                           sampleColumn) {

  print <- function(x) base::print(paste('[APPLY_UPSIMPLER] ', x))
  nSeeds <- length(targetSampleIDs)
  print(paste('Number of target samples:', nSeeds))

  synthDataDF <- base::data.frame()
  synthMetadataDF <- base::data.frame()
  for (i in base::seq_along(targetSampleIDs)) {
    targetSampleID <- targetSampleIDs[[i]]
    print(paste0('[', i, '/', nSeeds,
                 '] Working with seed sample ', targetSampleID,
                 ' from class ', metadataDF[targetSampleID, classColumn]))

    upsimplerUsedArgs$target_sample_id <- targetSampleID
    synths <- do.call(upsimpler$upsimple, upsimplerUsedArgs)

    synthDataDF <- base::rbind(synthDataDF, synths)
    synthsMeta <- base::data.frame(matrix(nrow = base::nrow(synths), ncol = 0))
    synthsMeta[[classColumn]] <- metadataDF[targetSampleID, classColumn]
    synthsMeta[[sampleColumn]] <- base::rownames(synths)
    synthsMeta[[higherClassColumn]] <- metadataDF[targetSampleID, higherClassColumn]
    synthsMeta[[domainColumn]] <- metadataDF[targetSampleID, domainColumn]

    rownames(synthsMeta) <- base::rownames(synths)
    synthMetadataDF <- base::rbind(synthMetadataDF, synthsMeta)
  }

  return(list(synthDataDF = synthDataDF, synthMetadataDF = synthMetadataDF))
}
