#' Classify test samples
#'
#' Function to classify new samples using the models generated with the reference cohort.
#'
#' @param modelList List containing the models generated by the Minority classifier.
#' @param testData Test data to be classified. The dataset contains only the variables needed as input for the classifier.
#'
#' @return Dataframe containing the classifications of the tumor subtypes for each sample within the Minority classifier.
#' Each row is a test sample, with the separate columns containing the classifications from the separate models.
#'
predictTest <- function(modelList, testData) {
  for (i in seq(1:length(modelList))) {
    model <- modelList[[i]]
    prediction <- stats:: predict(model, newdata=testData)

    if (i == 1) {
      result <- data.frame(fold1 = prediction)
    } else {
      result[, paste0("fold", i)] <- prediction
    }
  }

  return(result)
}
