#' Classify test samples
#'
#' Function to classify new samples using the models generated with the reference cohort.
#'
#' @param modelList List containing the models generated by the minority classifier.
#' @param test.data Test data to be classified. The dataset contains only the variables needed as input for the classifier.
#'
#' @return Dataframe containing the predictions of the tumor (sub)types for each sample within the minority classifier.
#' Each row is a test sample, with the separate columns containing the predictions from the separate models.
#' @export
#'
predictTest <- function(modelList, test.data) {
  for (i in seq(1:length(modelList))) {
    model <- modelList[[i]]
    prediction <- predict(model, newdata=test.data)

    if (i == 1) {
      result <- data.frame(fold1 = prediction)
    } else {
      result[, paste0("fold", i)] <- prediction
    }
  }

  return(result)
}
